apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ENVIRONMENT: "production"
  GATEWAY_HTTP_ADDR: ":8081"
  JAEGER_ENDPOINT: "http://jaeger:14268/api/traces"
  STRIPE_SUCCESS_URL: "http://localhost:3000?payment=success"
  STRIPE_CANCEL_URL: "http://localhost:3000?payment=cancel"