apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      containers:
        - name: driver-service
          image: europe-west1-docker.pkg.dev/{{PROJECT_ID}}/ride-sharing/driver-service
          env:
            # Jaeger endpoint
            - name: JAEGER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JAEGER_ENDPOINT
            # RabbitMQ credentials
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: uri
          ports:
            - containerPort: 9084
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: driver-service
spec:
  selector:
    app: driver-service
  ports:
    - port: 9084
      name: grpc
      targetPort: 9084
  type: ClusterIP